package models

import "time"

// Backup represents an encrypted backup file generated by user.
type Backup struct {
	ID        uint      `gorm:"primaryKey"`
	UserID    uint      `gorm:"index;not null"`
	FileName  string    `gorm:"size:255;not null"`
	FilePath  string    `gorm:"size:255;not null"`
	Size      int64     // bytes
	CreatedAt time.Time
	User      User `gorm:"constraint:OnDelete:CASCADE"`
}
